insert into movie (id, name, rating, duration) values (1, 'Final Cut, The', 3.4, 9597);
insert into movie (id, name, rating, duration) values (2, 'Rising Sun', 2.41, 3706);
insert into movie (id, name, rating, duration) values (3, 'Six Ways to Sunday', 3.53, 3890);
insert into movie (id, name, rating, duration) values (4, 'Ghoulies II', 3.93, 10740);
insert into movie (id, name, rating, duration) values (5, 'Frankenstein 90', 4.41, 7543);
insert into movie (id, name, rating, duration) values (6, 'Thunderbirds Are GO', 1.21, 9662);
insert into movie (id, name, rating, duration) values (7, 'Legally Blondes', 1.42, 7539);
insert into movie (id, name, rating, duration) values (8, 'Legend of Hell House, The', 2.49, 6750);
insert into movie (id, name, rating, duration) values (9, 'Känd från TV', 4.72, 6173);
insert into movie (id, name, rating, duration) values (10, 'Charge of the Light Brigade, The', 4.12, 4759);
insert into movie (id, name, rating, duration) values (11, 'Crime Story (Zhong an zu)', 4.07, 8227);
insert into movie (id, name, rating, duration) values (12, 'Killjoy 3', 1.51, 6562);
insert into movie (id, name, rating, duration) values (13, 'Violent Men, The', 3.39, 5147);
insert into movie (id, name, rating, duration) values (14, 'Merry War, A', 2.34, 10203);
insert into movie (id, name, rating, duration) values (15, 'Greyfriars Bobby (a.k.a. Greyfriars Bobby: The True Story of a Dog)', 4.79, 4949);
insert into movie (id, name, rating, duration) values (16, 'Inn in Tokyo, An (Tôkyô no yado)', 1.32, 8554);
insert into movie (id, name, rating, duration) values (17, 'As Cool As I Am', 4.6, 5538);
insert into movie (id, name, rating, duration) values (18, 'Tumannost Andromedy', 4.97, 6363);
insert into movie (id, name, rating, duration) values (19, 'Sidekicks', 1.25, 5720);
insert into movie (id, name, rating, duration) values (20, 'Sex, Lies, and Videotape', 3.26, 8042);
insert into movie (id, name, rating, duration) values (21, 'Arch of Triumph', 4.38, 7041);
insert into movie (id, name, rating, duration) values (22, 'Condemned, The', 5.0, 7894);
insert into movie (id, name, rating, duration) values (23, 'Battle of the Sexes, The', 1.63, 4205);
insert into movie (id, name, rating, duration) values (24, 'United', 1.19, 5346);
insert into movie (id, name, rating, duration) values (25, 'Tiptoes', 3.42, 5311);
insert into movie (id, name, rating, duration) values (26, 'Death by China ', 4.41, 6168);
insert into movie (id, name, rating, duration) values (27, 'Quantum of Solace', 4.14, 8026);
insert into movie (id, name, rating, duration) values (28, 'Prizzi''s Honor', 4.7, 10613);
insert into movie (id, name, rating, duration) values (29, 'Lucky One, The', 3.32, 7731);
insert into movie (id, name, rating, duration) values (30, 'Hear My Song', 1.42, 7719);
insert into movie (id, name, rating, duration) values (31, 'Blue Like Jazz', 1.62, 6241);
insert into movie (id, name, rating, duration) values (32, 'Three Comrades', 3.28, 6042);
insert into movie (id, name, rating, duration) values (33, 'Temptress Moon (Feng Yue)', 2.41, 3662);
insert into movie (id, name, rating, duration) values (34, 'Blue Vinyl', 1.7, 7857);
insert into movie (id, name, rating, duration) values (35, 'Breaking the Surface: The Greg Louganis Story', 4.46, 6502);
insert into movie (id, name, rating, duration) values (36, 'Mr. Saturday Night', 3.9, 9946);
insert into movie (id, name, rating, duration) values (37, 'Mouchette', 2.77, 8337);
insert into movie (id, name, rating, duration) values (38, 'Feet First', 4.95, 7294);
insert into movie (id, name, rating, duration) values (39, 'Electra, My Love (Szerelmem, Elektra)', 1.06, 6104);
insert into movie (id, name, rating, duration) values (40, 'Israeli Intelligence (Hamosad Hasagur)', 4.44, 6366);
insert into movie (id, name, rating, duration) values (41, 'Cottage Country', 3.75, 5389);
insert into movie (id, name, rating, duration) values (42, 'Teddy Bears'' Picnic', 3.75, 10471);
insert into movie (id, name, rating, duration) values (43, 'Doctor Takes a Wife, The', 4.99, 8580);
insert into movie (id, name, rating, duration) values (44, 'Daens', 2.3, 9930);
insert into movie (id, name, rating, duration) values (45, 'Smokey and the Bandit III', 1.22, 4989);
insert into movie (id, name, rating, duration) values (46, 'Friend Zone (Pagafantas)', 3.24, 8022);
insert into movie (id, name, rating, duration) values (47, 'Along Came Jones', 1.21, 4136);
insert into movie (id, name, rating, duration) values (48, 'Working Girl', 4.3, 8595);
insert into movie (id, name, rating, duration) values (49, 'Place Promised in Our Early Days, The (Kumo no mukô, yakusoku no basho)', 4.74, 7862);
insert into movie (id, name, rating, duration) values (50, 'Adam and Eve (Adão e Eva)', 2.0, 7278);
insert into movie (id, name, rating, duration) values (51, 'Continental Divide', 2.69, 5576);
insert into movie (id, name, rating, duration) values (52, 'Codes of Gender, The', 4.3, 4515);
insert into movie (id, name, rating, duration) values (53, 'Police Academy 3: Back in Training', 3.28, 6044);
insert into movie (id, name, rating, duration) values (54, 'Codes of Gender, The', 2.89, 9685);
insert into movie (id, name, rating, duration) values (55, 'Outbreak', 2.51, 3971);
insert into movie (id, name, rating, duration) values (56, 'Wedding Party, The (Die Bluthochzeit)', 2.62, 3963);
insert into movie (id, name, rating, duration) values (57, 'Super, The', 4.02, 9886);
insert into movie (id, name, rating, duration) values (58, 'Truce, The (a.k.a. La Tregua)', 1.78, 9154);
insert into movie (id, name, rating, duration) values (59, 'Riding the Bullet', 1.28, 7867);
insert into movie (id, name, rating, duration) values (60, 'Creep Van', 3.78, 8284);
insert into movie (id, name, rating, duration) values (61, '''71', 3.11, 6434);
insert into movie (id, name, rating, duration) values (62, 'Cold Creek Manor', 4.73, 4519);
insert into movie (id, name, rating, duration) values (63, 'More Wild Wild West', 4.88, 10418);
insert into movie (id, name, rating, duration) values (64, 'Our Idiot Brother', 1.19, 5829);
insert into movie (id, name, rating, duration) values (65, '8 Seconds', 2.71, 5832);
insert into movie (id, name, rating, duration) values (66, 'Hamburg Syndrome, The (Die Hamburger Krankheit)', 2.73, 6969);
insert into movie (id, name, rating, duration) values (67, 'Woman in Red, The', 1.02, 7648);
insert into movie (id, name, rating, duration) values (68, 'Crime Busters', 3.92, 8511);
insert into movie (id, name, rating, duration) values (69, 'Changeling', 2.91, 4120);
insert into movie (id, name, rating, duration) values (70, 'Muppets Take Manhattan, The', 2.12, 10230);
insert into movie (id, name, rating, duration) values (71, 'Tokyo Chorus (Tôkyô no kôrasu)', 3.35, 7976);
insert into movie (id, name, rating, duration) values (72, 'Shades of Ray', 3.28, 8147);
insert into movie (id, name, rating, duration) values (73, 'Hole, The', 3.81, 9093);
insert into movie (id, name, rating, duration) values (74, 'Sex, Lies, and Videotape', 2.04, 8408);
insert into movie (id, name, rating, duration) values (75, 'Primer', 3.64, 10492);
insert into movie (id, name, rating, duration) values (76, 'Labor Day', 1.2, 5078);
insert into movie (id, name, rating, duration) values (77, 'On the Line', 2.29, 9783);
insert into movie (id, name, rating, duration) values (78, 'Bending the Rules', 2.62, 7144);
insert into movie (id, name, rating, duration) values (79, 'Made for Each Other', 3.6, 5844);
insert into movie (id, name, rating, duration) values (80, 'Alien Abduction', 3.44, 6885);
insert into movie (id, name, rating, duration) values (81, 'Tupac: Resurrection', 1.66, 6097);
insert into movie (id, name, rating, duration) values (82, 'Lisa Picard is Famous (a.k.a. Famous)', 4.71, 9208);
insert into movie (id, name, rating, duration) values (83, 'Eye of the Dolphin', 1.62, 3664);
insert into movie (id, name, rating, duration) values (84, 'Wonder Woman', 2.68, 5824);
insert into movie (id, name, rating, duration) values (85, 'Torch Song', 3.02, 8378);
insert into movie (id, name, rating, duration) values (86, 'Love Affair, or the Case of the Missing Switchboard Operator (Ljubavni slucaj ili tragedija sluzbenice P.T.T.)', 2.86, 7728);
insert into movie (id, name, rating, duration) values (87, 'Dr. Jekyll and Mr. Hyde', 2.29, 5609);
insert into movie (id, name, rating, duration) values (88, 'Rosetta', 4.86, 8303);
insert into movie (id, name, rating, duration) values (89, 'Mina Tannenbaum', 4.58, 9303);
insert into movie (id, name, rating, duration) values (90, 'Turandot Project, The', 4.65, 4370);
insert into movie (id, name, rating, duration) values (91, 'Spooner', 2.71, 10368);
insert into movie (id, name, rating, duration) values (92, 'Centennial', 3.86, 9884);
insert into movie (id, name, rating, duration) values (93, 'Beautiful Mind, A', 4.53, 6439);
insert into movie (id, name, rating, duration) values (94, 'Eye Above the Well, The (Het oog boven de put)', 1.74, 7436);
insert into movie (id, name, rating, duration) values (95, 'Royal Affair, A (Kongelig affære, En)', 1.47, 5508);
insert into movie (id, name, rating, duration) values (96, 'Excess Baggage', 4.17, 6449);
insert into movie (id, name, rating, duration) values (97, 'Scandali nudi', 4.58, 5227);
insert into movie (id, name, rating, duration) values (98, 'Siffleurs, Les (Viheltäjät)', 3.79, 7427);
insert into movie (id, name, rating, duration) values (99, '7 Dollars on the Red (Sette dollari sul rosso)', 2.77, 8388);
insert into movie (id, name, rating, duration) values (100, 'Southerner, The', 2.9, 5353);