GET http://localhost:8987/Show/ShowInit

###

GET http://localhost:8987/Hall/HallInit

###

POST http://localhost:8987/api/Person/PersonAdd
Content-Type: application/json

{
  "name": "Hans"
}


###

POST http://localhost:8987/api/Csv/PersonDelete/3


###

POST http://localhost:8080/api/person
Content-Type: application/json

{
  "SSN": "987654321512",
  "dateOfBirth": "2021-01-01",
  "firstName": "Hans",
  "lastName": "Wurst",
  "isAwesome": true,
  "awesomeness": 2.3,
  "wealth": 122.56
}

###


GET http://localhost:8080/api/person/all
###

POST http://localhost:8080/api/address
Content-Type: application/json

{
  "personId": "123456789",
  "country": "Austria",
  "city": "Linz",
  "street": "Industriestrasse",
  "houseNo": 2
}
###

POST http://localhost:8080/api/address
Content-Type: application/json

{
  "personId": "12348789123",
  "country": "Austria",
  "city": "Linz",
  "street": "Industriestrasse",
  "houseNo": 4
}

###

GET http://localhost:8080/api/address/all

###

GET http://localhost:8080/api/person/citynames

###

GET http://localhost:8080/api/person/awesomepeoplecount
