POST http://localhost:8987/api/Person/PersonAdd
Content-Type: application/json

{
  "name": "Hans"
}


###

POST http://localhost:8987/api/Csv/PersonDelete/3


###
### All inits
GET http://localhost:8069/Person/PersonInit
###
GET http://localhost:8069/Ticket/TicketInit
###
GET http://localhost:8069/Show/ShowInit
###
GET http://localhost:8069/SeatCategory/SeatCategoryInit
###
GET http://localhost:8069/Seat/SeatInit
###
GET http://localhost:8069/Movie/MovieInit
###
GET http://localhost:8069/Hall/HallInit
###
GET http://localhost:8069/Employee/EmployeeInit
###
GET http://localhost:8069/Department/DepartmentInit
###
GET http://localhost:8069/Customer/CustomerInit